- name: "[ICINGA] Install Icinga"
  yum:
    name: icinga
    state: latest
  tags: icinga

- name: "[ICINGA] Install plugin"
  yum:
    name: nagios-plugins-all
    state: latest
  tags: icinga

- name: "[ICINGA] Enable icinga2"
  command: systemctl enable icinga2
  tags: icinga

- name: "[ICINGA] Install vim-icinga2"
  yum:
    name: vim-icinga2
    state: latest
  tags: icinga

- name: "[ICINGA] Add plugins"
  command: icinga2 feature enable ido-mysql
  tags: icinga