
- name: "[ICINGA] Enable icinga2"
  command: systemctl enable icinga2
  tags: icinga

- name: "[ICINGA] Add plugins"
  command: icinga2 feature enable ido-mysql
  tags: icinga

- name: "[ICINGA] Setup API Server"
  command: icinga2 api setup
  tags: icinga