- include_vars: ../vars/mysql.yml
  tags: mysql

- name: "[MYSQL] Be Sure MariaDB is OK"
  command: systemctl restart mariadb
  tags: mysql

- name: "[MYSQL] Create DataBase"
  command: mysql -u root -e "CREATE DATABASE icinga;"
  register: output
  failed_when: output.rc > 1
  tags: mysql

- name: "[MYSQL] Create USER and Flush Privilege"
  command: mysql -u root -e 'GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE VIEW, INDEX, EXECUTE on icinga.* to icinga@localhost identified by "icinga"; FLUSH PRIVILEGES;'
  failed_when: output.rc > 1
  tags: mysql

- name: "[MYSQL] Check if script already executed"
  command: ls /root/config_mysql.sh
  register: lsmysql
  failed_when: lsmysql.rc > 2
  tags: mysql

- name: "[MYSQL] Copy Script"
  copy:
    src: ../files/config_mysql.sh
    dest: /root/config_mysql.sh
    owner: root
    group: root
    mode: 740
  when: lsmysql.rc == 2
  tags: mysql

- name: "[MYSQL] Execute Script"
  command: bash /root/config_mysql.sh
  when: lsmysql.rc == 2
  tags: mysql

- name: "[MYSQL] Import conf using script"
  command: mysql -u root -e icinga < /usr/share/icinga2-ido-mysql/schema/mysql.sql
  tags: mysql