
- name: "[IPTABLES] Accept rule port 80"
  command: iptables -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
  tags: iptables

- name: "[IPTABLES] Accept rule port 443"
  command: iptables -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
  tags: iptables

- name: "[IPTABLES] Save rules"
  command: service iptables save
  tags: iptables